version: "3.2"

services:
  dev:
    container_name: green-aureus
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /var/www/green-aureus
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/green-aureus/.cargo
    volumes:
      - .:/var/www/green-aureus
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/green-aureus --dev --ws-external"